---
label: Product
hide_body: true
fields:
- name: name
  type: text
  config:
    required: false
  label: name
- name: description
  type: textarea
  default: ''
  config:
    required: false
    wysiwyg: false
    schema:
      format: markdown
  label: description
- name: price
  type: number
  label: price
  description: ''
  default: 0
  required: true
  config:
    min: 
    max: 
    step: 
- name: slug
  type: text
  config:
    required: false
  label: slug
pages:
- product/aircraft_carrier.md
- product/potato.md
